import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Enhanced CloudExtel Brand Colors with more vibrant options
        cloudextel: {
          navy: "#1e3a5f",
          "navy-dark": "#152d47",
          "navy-light": "#2a4a6b",
          blue: "#1e3a5f",
          "blue-muted": "#2a4a6b",
          "blue-accent": "#3b5f7d",
        },
        // Enhanced color palette for better visual pop
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#1e3a5f",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "#152d47",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "#152d47",
          foreground: "#f8fafc",
          primary: "#1e3a5f",
          "primary-foreground": "#f8fafc",
          accent: "#2a4a6b",
          "accent-foreground": "#f8fafc",
          border: "#2a4a6b",
          ring: "#1e3a5f",
        },
        // Vibrant accent colors for better visual pop
        emerald: {
          400: "#34d399",
          500: "#10b981",
          600: "#059669",
        },
        cyan: {
          400: "#22d3ee",
          500: "#06b6d4",
          600: "#0891b2",
        },
        purple: {
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
        },
        orange: {
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-glow": {
          "0%, 100%": {
            boxShadow: "0 0 5px rgba(34, 211, 238, 0.5)",
          },
          "50%": {
            boxShadow: "0 0 20px rgba(34, 211, 238, 0.8), 0 0 30px rgba(34, 211, 238, 0.4)",
          },
        },
        "slide-up": {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "slide-up": "slide-up 0.3s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    // Safelist dynamic color classes
    "from-emerald-500",
    "to-emerald-500",
    "from-emerald-500/10",
    "from-emerald-500/20",
    "to-emerald-600/20",
    "border-emerald-500/30",
    "text-emerald-400",
    "bg-emerald-500/20",
    "from-blue-500",
    "to-blue-500",
    "from-blue-500/10",
    "from-blue-500/20",
    "to-blue-600/20",
    "border-blue-500/30",
    "text-blue-400",
    "bg-blue-500/20",
    "from-green-500",
    "to-green-500",
    "from-green-500/10",
    "from-green-500/20",
    "to-green-600/20",
    "border-green-500/30",
    "text-green-400",
    "bg-green-500/20",
    "from-purple-500",
    "to-purple-500",
    "from-purple-500/10",
    "from-purple-500/20",
    "to-purple-600/20",
    "border-purple-500/30",
    "text-purple-400",
    "bg-purple-500/20",
    "from-orange-500",
    "to-orange-500",
    "from-orange-500/10",
    "from-orange-500/20",
    "to-orange-600/20",
    "border-orange-500/30",
    "text-orange-400",
    "bg-orange-500/20",
    "from-cyan-500",
    "to-cyan-500",
    "from-cyan-500/10",
    "from-cyan-500/20",
    "to-cyan-600/20",
    "border-cyan-500/30",
    "text-cyan-400",
    "bg-cyan-500/20",
    "from-yellow-500",
    "to-yellow-500",
    "from-yellow-500/10",
    "from-yellow-500/20",
    "to-yellow-600/20",
    "border-yellow-500/30",
    "text-yellow-400",
    "bg-yellow-500/20",
    "from-pink-500",
    "to-pink-500",
    "from-pink-500/10",
    "from-pink-500/20",
    "to-pink-600/20",
    "border-pink-500/30",
    "text-pink-400",
    "bg-pink-500/20",
    "from-red-500",
    "to-red-500",
    "from-red-500/10",
    "from-red-500/20",
    "to-red-600/20",
    "border-red-500/30",
    "text-red-400",
    "bg-red-500/20",
  ],
} satisfies Config

export default config
