# Optional: Docker setup for easy deployment
version: '3.8'

services:
  # Your existing backend (don't change this)
  backend:
    build: ./your-existing-backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    # Your existing backend configuration

  # New dashboard service
  dashboard:
    build: ./cloud-extel-dashboard
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      - backend

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - dashboard
